{-# LANGUAGE PatternSynonyms #-}
module Internal.GHC.API (
      ErrMsg(..)
    , SourceError
    , SourceText(..)
    , RealSrcSpan(..)
    , SrcSpan
    , SrcLoc(..)
    , GenLocated(..)
    , Located
    , FastString
    , bagToList
    , srcErrorMessages
    , noSrcSpan
    , fsLit, unpackFS
    , mkRealSrcLoc
    , srcSpanStartLine, srcSpanEndLine
    , srcSpanStartCol, srcSpanEndCol
    , mkRealSrcSpan
    , Name
    , NamedThing
    , RdrName
    , AvailInfo
    , CoreProgram
    , Dependencies
    , GlobalRdrEnv
    , FindResult(..)
    , Module(..)
    , ModuleName
    , ModuleGraph
    , HomeModInfo(..)
    , DesugaredModule(..)
    , TypecheckedModule(..)
    , ParsedModule(..)
    , HsModule(..)
    , HsParsedModule(..)
    , ModSummary(..)
    , ModLocation
    , ModGuts(..)
    , NameSet
    , UniqFM
    , IfM
    , RenamedSource
    , ClsInst
    , FamInst
    , Id
    , IdDetails(..)
    , TyCon
    , TyThing
    , DynFlags(..)
    , HasDynFlags
    , PromotionFlag(..)
    , TopLevelFlag(..)
    , TcGblEnv
    , IsBootInterface
    , Hsc
    , HscEnv
    , TcM
    , TcRn
    , TcRnExprMode(..)
    , GhcT
    , Ghc
    , GhcRn
    , GhcPs
    , ApiAnns
    , AnnotationComment
    , nameModule
    , moduleNameString
    , nameOccName
    , occNameString
    , nameStableString
    , nameSrcLoc
    , nameSrcSpan
    , nameSetElemsStable
    , getName
    , mkInternalName
    , mkVarOcc
    , availNames
    , alwaysQualifyNames
    , queryQualifyName
    , neverQualify
    , hsc_dflags
    , findExposedPackageModule
    , throwOneError
    , throwGhcExceptionIO
    , lookupHpt
    , thisPackage
    , fsToUnitId
    , getDynFlags
    , hscDesugar
    , hscTypecheckRename
    , hscParse
    , hsc_HPT
    , hscTcRcLookupName
    , lookupTypeHscEnv
    , lookupType
    , lookupTypeEnv
    , isBootSummary
    , getTopEnv
    , GhcMonad(..)
    , ParsedMod(..)

    , Outputable
    , SDoc
    , MsgDoc
    , Messages
    , showSDoc
    , showSDocDump
    , showSDocDebug
    , putLogMsg
    , ppr
    , PprStyle
    , Depth(..)
    , PrintUnqualified
    , Severity(..)
    , WarnReason(..)
    , defaultErrStyle
    , text
    , ptext
    , hsep
    , parens
    , quotes
    , (<+>)
    , panic
    , mkLongErrAt
    , mkUserStyle
    , renderWithStyle
    , FixityDirection(..)
    , Fixity(..)
    , Arity
    , Bag

    , Expr(..)
    , Class
    , Var(..)
    , Type(..)
    , Kind
    , LHsExpr
    , LHsType
    , LHsDecl
    , PredType
    , CoreExpr
    , CoreBind
    , Bind(..)
    , DataCon
    , AltCon(..)
    , TyVar
    , TyConBinder
    , Tickish(..)
    , Unique
    , Uniquable
    , HsDecl(..)
    , Sig(..)
    , AnonArgFlag(..)
    , noExtField
    , dataConInstArgTys
    , exprType
    , lintCoreBindings
    , synTyConRhs_maybe
    , isPrimTyCon
    , tyConTyVars
    , mkKindTyCon
    , tyConDataCons_maybe
    , lexprCtOrigin
    , getClassPredTys
    , tcRnLookupRdrName
    , isPromotedDataCon
    , isTupleDataCon

    -- * Shimmed
    , UnhelpfulSpanReason(..)
    , pattern RealSrcSpan
    , pattern UnhelpfulSpan
    , GenWithIsBoot(..)
    , getDependenciesModuleNames
    , dataConExTyVars 
    , pattern FunTy
    ) where

import Internal.GHC.API.Common
import Internal.GHC.API.Shim