# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda using `infix`"} # 4 hints
- ignore: {name: "Eta reduce"} # 51 hints
- ignore: {name: "Move guards forward"} # 2 hints
- ignore: {name: "Parse error: on input `,'"} # 1 hint
- ignore: {name: "Parse error: possibly incorrect indentation or mismatched brackets"} # 3 hints
- ignore: {name: "Redundant lambda"} # 7 hints
- ignore: {name: "Unused LANGUAGE pragma"} # 9 hints
- ignore: {name: "Use <&>"} # 3 hints
- ignore: {name: "Use camelCase"} # 61 hints
- ignore: {name: "Use fewer LANGUAGE pragmas"} # 2 hints
- ignore: {name: "Use first"} # 1 hint
- ignore: {name: "Use infix"} # 3 hints
- ignore: {name: "Use uncurry"} # 3 hints
